project:
  type: book

book:
  title: "Data Science Through Examples"
  author: "Santiago Zuluaga Ayala"
  date: "10/11/2022"
  chapters:
    - index.qmd
    - 01-p-values\p-values.qmd
    - 02-r-squared\r-squared.qmd
    - 03-bayes-theorem\bayes-theorem.qmd
    - 04-classification-metrics\classification-metrics.qmd

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

